### ISSUE TITLE
Mobile Toolbar icon?

### ISSUE THREAD

**Issue by mfloreen** [jose-elias-alvarez/obsidian-paste-link#10]
First, awesome plugin, I've had the same frustrations with the two plugins you've based this on, and your solution works just the way I hoped the other plugins would. Thank you!

One minor request: is it possible to change the icon used in the mobile toolbar (defaults to question mark)?

**Comment by jose-elias-alvarez** [comment]
Thanks, and good catch! Fixed in 401877e10c339c651ad62ce5ed9440bd3421fdf2 and released in 3.2.0.
