### ISSUE TITLE
Customise "standard paste" hotkey

### ISSUE THREAD

**Issue by jimmyjudas** [jose-elias-alvarez/obsidian-paste-link#4]
It'd be great to be able to customise the hotkey for the "standard paste" functionality as I already have `shift + cmd + v` set up as shortcut for a clipboard manager (Alfred).

**Comment by jose-elias-alvarez** [comment]
Sure, seems reasonable. I think the easiest way to do this would be to add a dedicated “just paste” command, which you’d then be able to map to whatever key you want. Would that handle your use case? If so, I’m happy to review a PR or take care of it myself whenever I have time.

**Comment by jose-elias-alvarez** [comment]
Added in 3e3faf3 and released in 2.0.0.
