### ISSUE TITLE
Fetch the YouTube page title

### ISSUE THREAD

**Issue by lymeswold** [jose-elias-alvarez/obsidian-paste-link#9]
There's a pull request in the Auto Link Title plugin to fetch the title for YouTube links, using the LinkPreview API ... this would be very useful. I'm not up to implementing it myself. Can I raise it as a PR?

"Using the LinkPreview API to get the page title by ZhymabekRoman · Pull Request #128 · zolrath/obsidian-auto-link-title · GitHub"

https://github.com/zolrath/obsidian-auto-link-title/pull/128

**Comment by jose-elias-alvarez** [comment]
It should be possible to use the same API here as well, but what issue are you having with YouTube page titles? For me fetching titles is working as expected.

**Comment by lymeswold** [comment]
Ah, I now see that on desktop Obsidian it **does** fetch the page title - thank you!  I use **mobile** Obsidian on a Chromebook running in the Android (13) container, where the video title is always set as "YouTube" rather than the actual title. Interestingly when I try the same on my Android phone (Android 14 on a Pixel 6 Pro) it pastes only the URL, with a blank title. Anyway, it may be that this is not an easy or even possible fix ... in which case I'll just remote to my desktop for pasting YouTube links.

**Comment by jose-elias-alvarez** [comment]
Good catch, I tested this out on mobile and replicated the issue. I guess YouTube is not returning the full title on mobile, so I put together a fix in b0677c0 and confirmed that it works on iOS and iPadOS. 

Could you update to 3.0.1 and let me know if it works on your environments?

**Comment by lymeswold** [comment]
That works now on Android (Chromebook & Pixel), Excellent, thank you.
